#!/usr/bin/env node

/**
 * Robust Hook Installation Script for c0ntextKeeper
 * Directly modifies ~/.claude/settings.json to configure PreCompact hook
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

// Colors for terminal output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m'
};

function log(message, color = '') {
  console.log(color + message + colors.reset);
}

function logSuccess(message) {
  log('✅ ' + message, colors.green);
}

function logError(message) {
  log('❌ ' + message, colors.red);
}

function logWarning(message) {
  log('⚠️  ' + message, colors.yellow);
}

function logInfo(message) {
  log('ℹ️  ' + message, colors.cyan);
}

async function installHook() {
  log('\n🚀 c0ntextKeeper Hook Installation', colors.bright + colors.blue);
  log('=====================================\n', colors.blue);

  // Step 1: Determine paths
  const homeDir = os.homedir();
  const claudeDir = path.join(homeDir, '.claude');
  const settingsPath = path.join(claudeDir, 'settings.json');
  const hooksDir = path.join(claudeDir, 'hooks');
  const projectDir = path.dirname(__dirname);
  const hookScriptPath = path.join(projectDir, 'dist', 'hooks', 'precompact.js');

  logInfo(`Claude directory: ${claudeDir}`);
  logInfo(`Settings file: ${settingsPath}`);
  logInfo(`Hook script: ${hookScriptPath}`);

  // Step 2: Check if hook script is built
  if (!fs.existsSync(hookScriptPath)) {
    logError('Hook script not found. Please run "npm run build" first.');
    logWarning('Run: cd ' + projectDir + ' && npm run build');
    process.exit(1);
  }
  logSuccess('Hook script found');

  // Step 3: Create Claude directory if needed
  if (!fs.existsSync(claudeDir)) {
    fs.mkdirSync(claudeDir, { recursive: true });
    logSuccess(`Created Claude directory: ${claudeDir}`);
  }

  // Step 4: Create hooks directory
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
    logSuccess(`Created hooks directory: ${hooksDir}`);
  }

  // Step 5: Read or create settings.json
  let settings = {};
  if (fs.existsSync(settingsPath)) {
    try {
      const content = fs.readFileSync(settingsPath, 'utf-8');
      settings = JSON.parse(content);
      logSuccess('Loaded existing settings.json');
    } catch (error) {
      logError(`Failed to parse settings.json: ${error.message}`);
      
      // Backup corrupted file
      const backupPath = settingsPath + '.backup.' + Date.now();
      fs.copyFileSync(settingsPath, backupPath);
      logWarning(`Backed up corrupted settings to: ${backupPath}`);
      
      settings = {};
    }
  } else {
    logInfo('No existing settings.json found, creating new one');
  }

  // Step 6: Configure PreCompact hook
  const hookCommand = `node ${hookScriptPath}`;
  const hookConfig = {
    matcher: '*',
    hooks: [{
      type: 'command',
      command: hookCommand
    }]
  };

  // Initialize hooks object if needed
  if (!settings.hooks) {
    settings.hooks = {};
  }

  // Check if PreCompact already has our hook
  let hookExists = false;
  if (settings.hooks.PreCompact) {
    hookExists = settings.hooks.PreCompact.some(config => 
      config.hooks && config.hooks.some(h => 
        h.command && h.command.includes('c0ntextKeeper')
      )
    );
  }

  if (hookExists) {
    logWarning('c0ntextKeeper hook already configured');
    logInfo('To reinstall, remove the existing hook from settings.json first');
  } else {
    // Add our hook configuration
    if (!settings.hooks.PreCompact) {
      settings.hooks.PreCompact = [];
    }
    settings.hooks.PreCompact.push(hookConfig);
    logSuccess('Added PreCompact hook configuration');
  }

  // Step 7: Write updated settings.json
  try {
    const settingsJson = JSON.stringify(settings, null, 2);
    fs.writeFileSync(settingsPath, settingsJson);
    logSuccess('Updated settings.json successfully');
  } catch (error) {
    logError(`Failed to write settings.json: ${error.message}`);
    process.exit(1);
  }

  // Step 8: Create wrapper script for better reliability
  const wrapperPath = path.join(hooksDir, 'c0ntextkeeper-hook.sh');
  const wrapperContent = `#!/bin/bash
# c0ntextKeeper PreCompact Hook Wrapper
# Auto-generated by install-hook.js

# Enable debug mode if C0NTEXTKEEPER_DEBUG is set
if [ "$C0NTEXTKEEPER_DEBUG" = "true" ]; then
  set -x
fi

# Log directory
LOG_DIR="$HOME/.c0ntextkeeper/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/hook.log"

# Log hook execution
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Hook triggered (PID: $$)" >> "$LOG_FILE"

# Execute the hook with Node.js
node "${hookScriptPath}" 2>> "$LOG_FILE"
EXIT_CODE=$?

# Log result
if [ $EXIT_CODE -eq 0 ]; then
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Hook completed successfully" >> "$LOG_FILE"
elif [ $EXIT_CODE -eq 2 ]; then
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Hook blocked compaction (exit code 2)" >> "$LOG_FILE"
else
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Hook failed with code $EXIT_CODE" >> "$LOG_FILE"
fi

exit $EXIT_CODE
`;

  try {
    fs.writeFileSync(wrapperPath, wrapperContent);
    fs.chmodSync(wrapperPath, '755');
    logSuccess(`Created wrapper script: ${wrapperPath}`);
  } catch (error) {
    logWarning(`Could not create wrapper script: ${error.message}`);
  }

  // Step 9: Display configuration summary
  log('\n📋 Configuration Summary', colors.bright + colors.cyan);
  log('========================\n', colors.cyan);
  
  console.log(colors.bright + 'Hook Configuration:' + colors.reset);
  console.log(JSON.stringify(hookConfig, null, 2));
  
  log('\n✨ Installation Complete!', colors.bright + colors.green);
  log('========================\n', colors.green);
  
  logInfo('Next steps:');
  console.log('1. Restart Claude Code (if currently running)');
  console.log('2. Open any project in Claude Code');
  console.log('3. Run /compact to trigger the hook');
  console.log('4. Check archives at: ~/.c0ntextkeeper/archive/');
  
  log('\n💡 Debugging:', colors.bright);
  console.log('- View logs: tail -f ~/.c0ntextkeeper/logs/hook.log');
  console.log('- Enable debug: export C0NTEXTKEEPER_DEBUG=true');
  console.log('- Verify hook: cat ~/.claude/settings.json | jq .hooks.PreCompact');
  console.log('- Test hook: c0ntextkeeper test-hook');
  
  log('\n📖 Documentation:', colors.bright);
  console.log('- Integration guide: ' + path.join(projectDir, 'HOOK-INTEGRATION.md'));
  console.log('- Project README: ' + path.join(projectDir, 'README.md'));
  
  // Step 10: Verify installation
  log('\n🔍 Verifying Installation...', colors.bright);
  
  // Check settings.json has our hook
  try {
    const verifySettings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    const hasHook = verifySettings.hooks?.PreCompact?.some(config => 
      config.hooks?.some(h => h.command?.includes(hookScriptPath))
    );
    
    if (hasHook) {
      logSuccess('Hook is properly configured in settings.json');
    } else {
      logError('Hook configuration not found in settings.json');
      process.exit(1);
    }
  } catch (error) {
    logError(`Verification failed: ${error.message}`);
    process.exit(1);
  }
  
  // Test hook can be executed
  try {
    const testCommand = `echo '{"hook_event_name":"test"}' | node ${hookScriptPath}`;
    require('child_process').execSync(testCommand, { stdio: 'pipe' });
    logSuccess('Hook script is executable');
  } catch (error) {
    logWarning('Hook script test failed (this is normal if c0ntextKeeper is not built)');
  }
  
  logSuccess('\n🎉 c0ntextKeeper hook is ready to use!');
}

// Handle errors gracefully
process.on('uncaughtException', (error) => {
  logError(`Unexpected error: ${error.message}`);
  console.error(error.stack);
  process.exit(1);
});

// Run installation
installHook().catch(error => {
  logError(`Installation failed: ${error.message}`);
  console.error(error.stack);
  process.exit(1);
});